#eureka configuration
spring.application.name=eurekaserver
server.port=${EUREKA_SERVER_PORT:8761}
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.enable-self-preservation=true
eureka.instance.lease-renewal-interval-in-seconds=30
eureka.instance.lease-expiration-duration-in-seconds=90
eureka.server.eviction-interval-timer-in-ms=60000
spring.profiles.active=native

#management configuration
management.server.ssl.enabled=false
management.endpoint.health.enabled=true
management.health.diskspace.enabled=false
management.endpoints.web.exposure.include=health, loggers, info
management.endpoints.web.path-mapping.loggers=loggers
management.endpoints.web.path-mapping.health=health
management.endpoints.web.path-mapping.info=info

management.endpoint.health.probes.add-additional-paths=true
management.server.port=${MANAGEMENT_SERVER_PORT:9000}